### PR TITLE
Develop1

### PR DESCRIPTION
**Pull request by Herb01**

### CODE REVIEW

**Comment by hobbymachinist** [comment]
This looks like a change specific to your platform / build environment. It's not something I would merge upstream sorry.

**Comment by ag-embedded** [comment]
In a very common platformIO development environment, the platform/tft_opencm3_stm32fx.c does not work. Herb01's solution works great.

**Comment by Herb01** [comment]
Hello,

I'm try to build your marvellous els design. However, Ii came up with 
some pitfalls. I ordered the PCB's and set everything up according to 
your documentation. It took me several weeks but finally this week i try 
for the first time to switch on the power. I only see the backlight of 
the LCD but nothing more. After investigation it seems like the LCD is 
not connected according to the settings in gpio.h. I see and measured 
the following connections:

PA0    TFT_D0
PA1    TFT_D1
PA2    TFT_D2
PA3    TFT_D3
PA4    TFT_D4
PB13    TFT_D5
PA14    TFT_D6
PA15    TFT_D7

The last three connections are not according to the software. Also the 
Z_ena is connected to PA5.

I'm confused. Did i use an older version of the PCB or is the setting in 
gpio.h wrong.

Please help.

Best regards,
Herbert Slaghekke

**Comment by hobbymachinist** [comment]
@Herb01  see https://github.com/hobbymachinist/els/blob/main/src/main.c#L30-L36

The GPIO map in gpio.h should match that, if not I can update the comments.

**Pull request closed without merging**
